language: node_js
node_js:
- '8'
cache:
  directories:
  - server/node_modules
  - server/client/node_modules
install:
- cd ./server
- npm install
# - npm run build
script:
- nohup npm run start &
- sleep 3
- npm run build --prefix client

# - npm run test
# - npm run lint

deploy:
    provider: heroku
    api_key: 658742ce-2954-4b44-be8b-723b024f062a
    app: daledger
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master

notifications:
    email:
        recipients:
            - emerysolutions@yahoo.co.uk
        on_success: never 
        on_failure: always 
