language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script: cd ./server/client && npm install
script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
  
