language: node_js
before_install: 
  - cd ./server
  - npm install && node index.js &
before_script: cd ./client && npm install
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run test
  - npm run lint
  - npm run build

deploy:
    provider: heroku
    api_key: 658742ce-2954-4b44-be8b-723b024f062a
    app: daledger
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master

notifications:
    email:
        recipients:
            - emerysolutions@yahoo.co.uk
