language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script: cd ./server/client && npm install
script:
  - npm test
  - npm run build

deploy:
  provider: heroku
  api_key: 782e3428-c9af-41c0-9555-ee83a9605a9e
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  
