language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script: cd ./server/client && npm install
script:
  - npm test
  - npm run build

deploy:
  provider: heroku
  api_key: 658742ce-2954-4b44-be8b-723b024f062a
  app: daledger
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  
